sudo: required
dist: trusty
# Force travis to use its minimal image with default Python settings
language: generic

env:
  global:
    - ROS_DISTRO="kinetic" UPSTREAM_WORKSPACE=file #This expects a file .travis.rosinstall available at the top directory
install:
  - git clone --depth=1 https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh
